name: Package & Smoke Test

on:  # yamllint disable-line rule:truthy
  pull_request:
  push:
    branches:
    - master
    - next/*
    - release/*
    - feat/per-commit-without-kbt

env:
  DOCKER_REPOSITORY: kong/kong-build-tools
  DOCKER_RELEASE_REPOSITORY: kong/kong

jobs:
  package-and-test:
    if: github.event_name == 'pull_request'
    name: Build & Smoke Test Packages
    runs-on: ubuntu-22.04

    steps:
    - name: Setup some environment variables
      run: |
        echo "KONG_SOURCE_LOCATION=$GITHUB_WORKSPACE/kong-src" >> $GITHUB_ENV
        echo "KONG_BUILD_TOOLS_LOCATION=$GITHUB_WORKSPACE/kong-build-tools" >> $GITHUB_ENV

    - name: Checkout Kong source code
      uses: actions/checkout@v3
      with:
        path: ${{ env.KONG_SOURCE_LOCATION }}
        submodules: recursive

    - name: Setup package naming environment variables
      run: |
        grep -v '^#' ${{ env.KONG_SOURCE_LOCATION}}/.requirements >> $GITHUB_ENV

    - name: Swap git with https
      run: git config --global url."https://github".insteadOf git://github

    - name: Package
      run: |
          cd ${{ env.KONG_SOURCE_LOCATION }} && \
          make package/deb

    - name: Package Smoke Test
      run: |
          cd ${{ env.KONG_SOURCE_LOCATION }} && \
          make package/test/deb

  package-test-and-unofficial-release:
    if: github.event_name == 'push'
    name: Build & Smoke & Unofficial Release Packages
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        architecture: [amd64, arm64]
        package_type: [deb, rpm, apk]

    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Setup some environment variables
      run: |
        echo "KONG_SOURCE_LOCATION=$GITHUB_WORKSPACE/kong-src" >> $GITHUB_ENV
        echo "KONG_BUILD_TOOLS_LOCATION=$GITHUB_WORKSPACE/kong-build-tools" >> $GITHUB_ENV
        echo "ARCHITECTURE=${{ matrix.architecture}}" >> $GITHUB_ENV

    - name: Checkout Kong source code
      uses: actions/checkout@v3
      with:
        path: ${{ env.KONG_SOURCE_LOCATION }}
        submodules: recursive

    - name: Setup package naming environment variables
      run: |
        grep -v '^#' ${{ env.KONG_SOURCE_LOCATION}}/.requirements >> $GITHUB_ENV
        echo "KONG_BUILD_TOOLS_LOCATION=$GITHUB_WORKSPACE/kong-build-tools" >> $GITHUB_ENV
        echo "DOCKER_RELEASE_REPOSITORY=kong/kong" >> $GITHUB_ENV
        echo "KONG_TEST_CONTAINER_TAG=colin-${GITHUB_REF_NAME##*/}-${{ matrix.package_type }}" >> $GITHUB_ENV
        if [[ ${{matrix.package_type }} == "apk" ]]; then
          echo "ADDITIONAL_TAG_LIST=colin-${GITHUB_REF_NAME##*/}-alpine" >> $GITHUB_ENV
        fi
        if [[ ${{matrix.package_type }} == "deb" ]]; then
          echo "ADDITIONAL_TAG_LIST=${GITHUB_REF_NAME##*/}-debian ${GITHUB_REF_NAME##*/} $GITHUB_SHA" >> $GITHUB_ENV
        fi

    - name: Swap git with https
      run: git config --global url."https://github".insteadOf git://github

    - name: Package
      run: |
        cd ${{ env.KONG_SOURCE_LOCATION }} && \
        make package/${{ matrix.package_type }}

    - name: Package Smoke Test
      run: |
        cd ${{ env.KONG_SOURCE_LOCATION }} && \
        make package/test/${{ matrix.package_type }}

    - name: Push Docker Image
      continue-on-error: true
      env:
        SKIP_TESTS: true
      run: |
        pushd ${{ env.KONG_SOURCE_LOCATION }}
        make release/docker/${{ matrix.package_type }}

    - name: Store the package artifacts
      continue-on-error: true
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.package_type }}
        path: ${{ env.KONG_SOURCE_LOCATION }}/package/*

    - name: Comment on commit
      continue-on-error: true
      # peter-evans/commit-comment@v2
      uses: peter-evans/commit-comment@a9352b8603f5dfe736429a2fd438c09ed567dc83
      with:
        token: ${{ secrets.GHA_COMMENT_TOKEN }}
        body: |
          Docker image available ${{ env.DOCKER_RELEASE_REPOSITORY }}:${{ env.KONG_TEST_CONTAINER_TAG }}
          Artifacts avaialble https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
